### ISSUE TITLE
Chaos Dashboard To-Do List 🧱

### ISSUE THREAD

**Issue by g1eny0ung** [chaos-mesh/chaos-mesh#1283]
This issue is using to tracking the progress of the Chaos Dashboard development.

If you have any questions or suggestions, feel free to comment below. 🙋‍♀️🙋‍♂️

### #1546

- [x] (perf) Clearer search

### #1496

- [x] (chore) Consider an alternative to dayjs (Because it's not very mature
- [x] Use https://nivo.rocks/?

### #1458

- [ ] (test) Component-MUI tests in UI

### #1449

- [x] (chore) Advanced settings (Include debug mode, etc.)
- [x] (feat) Display Chaos Mesh version in UI

### #1374

- [x] (test) API tests in UI

### #1285

- [x] (refactor) Make the homepage more like a dashboard
- [x] (feat) Tourist Guide on home page
- [x] (feat) Predefined experiments (Can be store in the IndexedDB)
- [x] (chore) Security Mode support in UI
- [x] (feat) Download experiment YAML definition
- [x] (feat) Embed Swagger API
- [x] (chore) Delete archive experiments by UI interface

**Comment by zerefwayne** [comment]
Hello, @g1eny0ung I've been trying to use Chaos Mesh since past few weeks. I like the functionalities on the dashboard, just wanted to ask if improvements on ChaosMesh Dashboard can be a project in CNCF LFX Mentorship program?

**Comment by g1eny0ung** [comment]
> Hello, @g1eny0ung I've been trying to use Chaos Mesh since past few weeks. I like the functionalities on the dashboard, just wanted to ask if improvements on ChaosMesh Dashboard can be a project in CNCF LFX Mentorship program?

Currently no. We are still exploring the ease of use of the dashboard, and perhaps in the future, we will disassemble more independent functions to provide to the LFX Mentorship program。
