### ISSUE TITLE
Upload build-env and dev-env to the ghcr.io

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#2257]
## Feature Request

This feature can be split into several things:

- [x] Support override image registry and project in `Makefile` https://github.com/chaos-mesh/chaos-mesh/pull/2250
- [x] Pull these image from the `ghcr.io` rather than building them from scratch by default #2277
- [x] <del>Run CI without building `ghcr.io` if the specific label is not set</del> #2277
- [x] Automatically upload latest build-env and dev-env to `ghcr.io` when related PR is merged. #2277
- [x] Build arm64 `build-env` and `dev-env` image and upload to `ghcr.io`. https://github.com/chaos-mesh/chaos-mesh/pull/2318
- [x] #2317
- [x] #2322
- [ ] Docs! Docs! Docs!

Related with #2146

**Comment by STRRL** [comment]
Could we also move image `pingcap/chaos-mesh:latest` to `ghcr.io/chaos-mesh/chaos-mesh:latest`?
