### ISSUE TITLE
Release v2.2.0

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2608]
Here is the tracking issue for the next Chaos Mesh release: v2.2.0.

Feel free to comment suggestions and ask anything in this issue. :smile:  

Note: We are sliting this to-do list, moving part of them(marked with strikethrough) into the next minor release (v2.3.0).

## New Features && Enhancements

- [ ] ~Telemetry and Analytics, maybe using https://opentelemetry.io/~
- [x] P1 Azure Chaos
  - [x] VM stop/restart, disk detach https://github.com/chaos-mesh/chaos-mesh/pull/2821 
- [ ] P1 JVMChaos: client-side MySQL, RocketMQ Chaos
  - [ ] chaosd
    - [ ] MySQL Client Chaos: https://github.com/chaos-mesh/chaosd/pull/106  
    - [ ] RocketMQ
- [ ] ~KafkaChaos: broker stress pressure~
- [ ] ~TimeChaos: TimeStop~
- [x] https://github.com/chaos-mesh/chaos-mesh/issues/2401 and https://github.com/chaos-mesh/chaos-mesh/pull/2742
- [ ] P1 PhysicalMachineChaos
    - [ ] porting HTTPChaos from chaos-mesh to chaosd
    - [ ] porting IOChaos from chaos-mesh to chaosd
    - [x] Authentication Solutions https://github.com/chaos-mesh/chaos-mesh/issues/2390
    - [ ] https://github.com/chaos-mesh/chaosd Automatic Deployment/Delivery https://github.com/chaos-mesh/chaosd/issues/108
- [ ] P1 Chaos Mesh Components Healthy Check
- [x] P1 Statu Check
  - [ ] RFC https://github.com/chaos-mesh/rfcs/pull/39
  - [ ] Tracking Issue: https://github.com/chaos-mesh/chaos-mesh/issues/2929
- [ ] P1 Chaos Experiement Forcely Recover
  - [ ]  https://github.com/chaos-mesh/chaos-mesh/pull/2992
- [x] Timechaos support experiments overlapping https://github.com/chaos-mesh/chaos-mesh/pull/2942
- [x] Refined TimeChaos recover mechanism https://github.com/chaos-mesh/chaos-mesh/pull/2942
  - [x] graceful shutdown for each components
    - [x] https://github.com/chaos-mesh/chaos-mesh/pull/2668
- [ ] P2 BlockChaos 
  - [x] https://github.com/chaos-mesh/chaos-driver #2739 
  - [ ] https://github.com/chaos-mesh/chaos-mesh/pull/2907
- [ ] P1 HTTPChaos https://github.com/chaos-mesh/chaos-mesh/issues/3062
	- [ ] client-side HTTPChaos
	    - [x] https://github.com/chaos-mesh/chaos-mesh/pull/2555
	    - [ ] https://github.com/chaos-mesh/chaos-mesh/issues/2971
	- [ ] ~~HTTPS/TLS support~~
- [x] P2 StressChaos: refined memory stress implementation #2623 
- [ ] P2 Chaos Mesh Observability(logs, metrics and maybe traces)
  - [ ]  https://github.com/chaos-mesh/chaos-mesh/pull/3030
- [ ] P0 unified error and logging library (golang)
	- RFC about errors: https://github.com/chaos-mesh/rfcs/pull/24
	- RFC about logging: https://github.com/chaos-mesh/rfcs/pull/28
	- logging tracking issue: https://github.com/chaos-mesh/chaos-mesh/issues/2752
- [ ] P0 Refined Workflow UX on Chaos Dashboard
- [ ] ~~P0 Experiment Observability(Hold)~~
  - feature request: https://github.com/chaos-mesh/chaos-mesh/issues/2683
  - RFC: (https://github.com/chaos-mesh/rfcs/pull/38) 
  - Discussion: https://github.com/chaos-mesh/chaos-mesh/discussions/3012
- [ ] ~~Porting DiskChaos from chaosd to chaos-mesh~~
- [ ] ~~Refined NetworkChaos recovery mechanism~~
- [ ] ~~P2 ARM64 support~~
    - [ ] TimeChaos https://github.com/chaos-mesh/chaos-mesh/issues/2634
    - [ ] IOChaos
- [ ] P2 tidy helm charts https://github.com/chaos-mesh/chaos-mesh/issues/3015
- [x] tidy makefile  #2640 
	- RFC: https://github.com/chaos-mesh/rfcs/pull/27
	- https://github.com/chaos-mesh/chaos-mesh/pull/2771
- [ ] P2 unit test and e2e test on Chaos Dashboard
- [ ] P1 generated model based on openapi on Chaos Dashboard https://github.com/chaos-mesh/chaos-mesh/issues/2615
- [ ] P0 Kubernete API
	- [ ] API subgroup https://github.com/chaos-mesh/chaos-mesh/issues/2635
	- [ ] multi-version API https://github.com/chaos-mesh/chaos-mesh/issues/2601

About Documentation: https://github.com/chaos-mesh/website/milestone/1

Release Date: ~~March~~ April 2022

**Comment by anuragpaliwal80** [comment]
So all this new cool stuff is coming with `2.2.0` ?

**Comment by STRRL** [comment]
> So all this new cool stuff is coming with `2.2.0` ?

No, the roadmap is still updating, it might remove some items. our team evaluates workloads in the next several months, it would be finished in one or two weeks. Please keep looking forward to Chaos Mesh 2.2.0.

**Comment by anuragpaliwal80** [comment]
Ok. Thanks for update. I will vote for the HTTP one (if possible).

**Comment by anuragpaliwal80** [comment]
@STRRL So `HTTPS` support will be coming with 2.2 release ? Correct ?

**Comment by STRRL** [comment]
> @STRRL So `HTTPS` support will be coming with 2.2 release ? Correct ?

YES!

**Comment by anuragpaliwal80** [comment]
I am assuming that client-side HTTPChaos will support HTTPS. Correct ? @STRRL

**Comment by STRRL** [comment]
> I am assuming that client-side HTTPChaos will support HTTPS. Correct ? @STRRL 

PTAL @Hexilee @Andrewmatilde

**Comment by ashishgoyal111** [comment]
@STRRL I could see that query param based support is not there in current offering of HTTPChaos. We have a use-case where HTTPChaos is applied only when request received has certain attributes in the query params with certain values. Can you confirm if this feature is also a part of this upgrade? TIA.

**Comment by ashishgoyal111** [comment]
> @STRRL I could see that query param based support is not there in current offering of HTTPChaos. We have a use-case where HTTPChaos is applied only when request received has certain attributes in the query params with certain values. Can you confirm if this feature is also a part of this upgrade? TIA.

@Hexilee @Andrewmatilde Could you please help us know if we are planning to have query param based filters for HTTP chaos. Could you also refer us to some PR or proposal/wiki doc for client side(egress) HTTPChaos support.

**Comment by STRRL** [comment]
> Hi, I am curious about the support for Kubernetes v1.23
> 
> Thanks

Hi! Chaos Mesh would keep forward compatibility with the current/latest and future Kubernetes if there are no breaking changes introduced.

And latest release 2.1.3 also works well on kubernetes v1.23.4.

If you meet any problem, feel free to open an issue!
