### ISSUE TITLE
Tracking Refine Logging 

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2752]
## Refine Logging

As mentioned in https://github.com/chaos-mesh/rfcs/pull/28, we're going to migrate loggers to logr.

TODO List:

- [ ] Upgrade controller-runtime to `0.11.0` (relates upgrading logr dependency from 0.4 to 1.2)
- [ ] refine fx dependency injection, inject the root logger
- [ ] WIP: (migrate logger for each go packages)
