### ISSUE TITLE
Tracking issue: create CHANGELOG.md for active branches

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2799]
As this RFC https://github.com/chaos-mesh/rfcs/blob/main/text/2022-01-17-keep-a-changelog.md says, we would keep a changelog for chaos mesh in the future :tada:

This is a tracking issue for creating `CHANGELOG.md` for each active branches

- [x] `CHANGELOG.md` for `master` branch https://github.com/chaos-mesh/chaos-mesh/pull/2798
- [x] `CHANGELOG.md` for `release-2.1` branch https://github.com/chaos-mesh/chaos-mesh/pull/2801
- [x] `CHANGELOG.md` for `release-2.0` branch https://github.com/chaos-mesh/chaos-mesh/pull/2800
- [ ] Update release guideline, https://github.com/chaos-mesh/chaos-mesh/pull/2762
- [x] CI check updating CHANGELOG.md for each PR  https://github.com/chaos-mesh/chaos-mesh/issues/3134
- [x] Update PR templates https://github.com/chaos-mesh/chaos-mesh/pull/3148

**Comment by STRRL** [comment]
The "Release Guide" requires more updates except for CHANGELOG, so it is not suitable to keep tracking that PR in this issue.  

I am going to close this issue.
