### ISSUE TITLE
Tracking Issue: tidy helm chart

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3015]
## Feature Request

Make helm chart easier to use and maintenance.

Steps:
 
- [x] enriching comments in `values.yaml` https://github.com/chaos-mesh/chaos-mesh/pull/3053
- [x] make chaos-dashboard use another seviceaccount, split from serviceaccount used by chaos-controller-manager https://github.com/chaos-mesh/chaos-mesh/pull/3145
- [x] split cert and webhooks manifests https://github.com/chaos-mesh/chaos-mesh/pull/3159
- [ ] fix ambiguous helm values
	- [x] `dashboard.securityMode` for both chaos-dashboard RBAC and chaos-daemon mTLS https://github.com/chaos-mesh/chaos-mesh/pull/3168
	- [x] `webhook.FailurePolicy` is not applied to all the webhooks https://github.com/chaos-mesh/chaos-mesh/pull/3184
	- [ ] ~~use different configurable CA and cert keypair for "CRD webhook", "chaos-daemon mtls" and "chaosd mtls"~~
    - [x] use `webhook.crtPEM` for both "webhook server cert" and "clientConfig.caBundle", and nowhere to provide custom `caBundle` https://github.com/chaos-mesh/chaos-mesh/pull/3190
~~- [ ] cleanup usage of not-schema `env`~~
- [x] migration documentation, tracking issue: https://github.com/chaos-mesh/website/issues/281

**Comment by STRRL** [comment]
I am going to close this issue with successor: https://github.com/chaos-mesh/chaos-mesh/pull/3159
