### ISSUE TITLE
Feature Tracking: HTTPChaos

### ISSUE THREAD

**Issue by Hexilee** [chaos-mesh/chaos-mesh#3062]
## Feature Request

- [x] server-side HTTPChaos #1858
- [ ] client-side HTTPChaos
	- [x] #2555
	- [ ]  #2971
	- [ ] new options to differentiate client-side from server one.
- [ ] HTTPS support
- [ ] custom body injection plugins	
	- [ ] [PENDING] chaos-tproxy implementation https://github.com/chaos-mesh/chaos-tproxy/pull/19

**Comment by STRRL** [comment]
We are still working on the TLS part, so I am afraid that we would not bring HTTPCHaos with TLS support in Release 2.2.

**Comment by Hexilee** [comment]
> We are still working on the TLS part, so I am afraid that we would not bring HTTPCHaos with TLS support in Release 2.2.

Yes, I'm sorry about that.

**Comment by Hexilee** [comment]
> > We are still working on the TLS part, so I am afraid that we would not bring HTTPCHaos with TLS support in Release 2.2.
> 

Yes, I'm sorry for removing it from the v2.2 milestone.

**Comment by anuragpaliwal80** [comment]
So can I assume active work to enable this TLS feature will be continued in this area and it will not be paused/dropped?
We especially look for HTTPS support for egress calls.

**Comment by Hexilee** [comment]
> So can I assume active work to enable this TLS feature will be continued and it will not be paused/dropped? We especially look for HTTPS support for egress calls.

Hi, this feature will not be dropped but may be pending. Our team will discuss the work for this quarter today, then I will reply to you after the decision is made.

**Comment by Hexilee** [comment]
> > So can I assume active work to enable this TLS feature will be continued and it will not be paused/dropped? We especially look for HTTPS support for egress calls.
> 
> Hi, this feature will not be dropped but may be pending. Our team will discuss the work for this quarter today, then I will reply to you after the decision is made.

@anuragpaliwal80  We decide to work on this feature for this quarter.

**Comment by anuragpaliwal80** [comment]
Thanks for the update and for making it part of active development.

**Comment by STRRL** [comment]
HTTPChaos TLS Support has been completed in https://github.com/chaos-mesh/chaos-mesh/pull/3647

Not very sure about the roadmap of WASM Plugin, so I will still keep this issue open, and move it to milestone 2.6.
