### ISSUE TITLE
Tracking issue: migrate e2e test from Jenkins to GitHub Actions

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3086]
❤️ CNCF provides us with an unlimited quota with GitHub Actions, so we are going to migrate tests and release pipeline from Jenkins to GitHub Action.

steps: 

- [x] Setup e2e tests on master branch https://github.com/chaos-mesh/chaos-mesh/pull/2986  https://github.com/chaos-mesh/chaos-mesh/pull/3085
- [x] update tichi/prow bot configuration on master branch https://github.com/ti-community-infra/configs/pull/550
- [x] cherry-pick to release-2.1 https://github.com/chaos-mesh/chaos-mesh/pull/3087
- [x] update tichi/prow bot configuration on release-2.1 https://github.com/ti-community-infra/configs/pull/554
- [x] disable jenkins job (I have disabled the project and the webhook on Jenkins)
- [ ] update document test scope in supported release https://github.com/chaos-mesh/website/pull/270

Other related changes/optimizations:
- https://github.com/chaos-mesh/chaos-mesh/pull/3085
- https://github.com/chaos-mesh/chaos-mesh/pull/3090
