### ISSUE TITLE
Tracking issue: Going to release 2.2.0

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3202]
TODO:

- [ ] prune block chaos
- [ ] bump version to 2.2.0
- [ ] create release on github
- [ ] publish helm chart
