### ISSUE TITLE
Tracking Issue: prepare for release 2.3.0, feature status

### ISSUE THREAD

**Issue by Hexilee** [chaos-mesh/chaos-mesh#3361]
We plan to publish release 2.3.0 in the last week of July 2022, so we need to track the features that should be included. 

Uncompleted features should be carried with 2.3.0:

- [ ] ~https://github.com/chaos-mesh/chaos-mesh/issues/3341~
- [ ] TLS support for HTTPChaos
    - [x] chaos-tproxy implementation https://github.com/chaos-mesh/chaos-tproxy/pull/39
    - [ ] ~~https://github.com/chaos-mesh/chaos-mesh/issues/3062~~
- [ ] ~~https://github.com/chaos-mesh/chaos-mesh/pull/3079~~
- [x] https://github.com/chaos-mesh/chaos-mesh/pull/2907 
- [x] https://github.com/chaos-mesh/chaos-mesh/pull/3277
- [ ] ~Multi-version API https://github.com/chaos-mesh/chaos-mesh/pull/3009~
- [x] UI of new workflow
    - [x] https://github.com/chaos-mesh/chaos-mesh/pull/3185
    - [x] https://github.com/chaos-mesh/chaos-mesh/pull/3254
    - [x] https://github.com/chaos-mesh/chaos-mesh/pull/3368 

Features may be carried (not started):
- [x] https://github.com/chaos-mesh/chaos-mesh/issues/3157
    - [x] https://github.com/chaos-mesh/chaos-mesh/pull/3395
- [x] graceful restart
    - [ ] ~~https://github.com/chaos-mesh/chaos-mesh/pull/3312~~

**Comment by Hexilee** [comment]
I think we should carry the UI of new workflow in release 2.3.0 #3185 #3254 #3368, shall we? @STRRL @cwen0 @YangKeao

**Comment by STRRL** [comment]
> I think we should carry the UI of new workflow in release 2.3.0 #3185 #3254 #3368, shall we? @STRRL @cwen0 @YangKeao


+1 

I am very excited about the incoming updates about new UI of Workflow. 🤩🤩🤩

After these 3 PRs merged, could we mark the new Workflow UI as stable. Or there are still several features to be done, we'd better keep it as "technical preview". What do you think about it? @g1eny0ung

**Comment by STRRL** [comment]
tracking in: https://github.com/chaos-mesh/chaos-mesh/issues/3463
