### ISSUE TITLE
Tracking Issue: Release 2.3.0

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3463]
I am very happy that we're going to prepare the next minor release: 2.3.0

Refs to the [Release Cycle](https://github.com/chaos-mesh/chaos-mesh/discussions/3256), 2.3.0 will be released next week (July 25, 2022 - July 31, 2022).

There is still something to be done before we could release 2.3.0:

- [x] prepare the release notes 
  - [x] Draft: https://docs.google.com/document/d/1R5bTf8QKL0z8lR_vkS2FtgHZUDR-i_kSTDX3kz00uSQ/edit#
- [x] collect the codes that need to be pruned
  - [x] Multicluster https://github.com/chaos-mesh/chaos-mesh/pull/3471
- [x] finish uncompleted tasks that should be carried with 2.3.0
  - [x] https://github.com/chaos-mesh/chaos-mesh/pull/3462
  - [x] ~~https://github.com/chaos-mesh/chaos-mesh/issues/3169~~ won't be carried with 2.3.0
  - [x] https://github.com/chaos-mesh/chaos-mesh/issues/2822
  - [x] https://github.com/chaos-mesh/chaos-mesh/pull/3030
  - [x] https://github.com/chaos-mesh/chaos-mesh/pull/3449
- [x] cut the branch `release-2.3`
	- [x] create the new branch
	- [x] update the configurations in ti-community-infra/configs https://github.com/ti-community-infra/configs/pull/607 https://github.com/ti-community-infra/configs/pull/609
	- [x] update PR template, GitHub labels on PR/Issues https://github.com/chaos-mesh/chaos-mesh/pull/3490
	- [x] ~~bump the version to 2.3.0~~ after #3293 we do not need to manually update version in `helm/chaos-mesh` anymore
- [x] complete the code prune
- [ ] docs need to be updated
  - [ ] BlockChaos  https://github.com/chaos-mesh/website/pull/329
- [x] release the beta release
- [x] release the minor release
- [x] update changelog
  - [x] branch `release-2.3` https://github.com/chaos-mesh/chaos-mesh/pull/3508
  - [x] branch `master` https://github.com/chaos-mesh/chaos-mesh/pull/3509

**Comment by STRRL** [comment]
Yeah! We are running the release process for 2.3.0.
