### ISSUE TITLE
Tracking Issue: Adopt scarf.sh

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#4542]
### Chaos Mesh Version

N/A

### Kubernetes Version

N/A

### Describe the bug

Here is the tracking issue for things need to do, for adopting scarf.sh

- [ ] website pixel updating
- [ ] ticket on CNCF servicesdesk for subscription
- [ ] DNS record
- [ ] update helm chart
- [ ] release new verison
