### ISSUE TITLE
Tracking issue for supporting multiple rules of NetworkChaos

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#718]
This is the tracking issue and discussion board for the implementation of #687 

- [x] Refrace `NetworkChaos` to organize iptables rules into chain #721 
- [x] Add E2E test for `NetworkChaos`
- [ ] Implement `RawPodNetworkChaos` for single rule #788 
- [ ] ~~Fix the [bug](https://github.com/kubernetes-sigs/controller-runtime/issues/845) for controller-runtime (to support kubernetes 1.14)~~
- [ ] Refractor `NetworkChaos` to use `RawPodNetworkChaos` #788 
- [ ] Support multiple rules for `RawPodNetworkChaos` without considering overlapping ipsets #788
- [ ] Support overlapping ipsets for `RawPodNetworkChaos`

**Comment by Gallardot** [comment]
> * Fix the [bug](https://github.com/kubernetes-sigs/controller-runtime/issues/845) for controller-runtime (to support kubernetes 1.14)

@YangKeao I have a workaround on https://github.com/chaos-mesh/chaos-mesh/pull/338#issuecomment-599853819. Do you need `Delete validation` for `Validator` ?

**Comment by YangKeao** [comment]
> > * Fix the [bug](https://github.com/kubernetes-sigs/controller-runtime/issues/845) for controller-runtime (to support kubernetes 1.14)
> 
> @YangKeao I have a workaround on [#338 (comment)](https://github.com/chaos-mesh/chaos-mesh/pull/338#issuecomment-599853819). Do you need `Delete validation` for `Validator` ?

Yes. It would be better to have a `DELETE` validation here, but maybe it's not a necessity :thinking: .
